apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pocket-id-tls
  namespace: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: pocket-id-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pocket-id.corp.mulliken.net
