---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  encryptedData:
    ENCRYPTION_KEY: AgBAd61kVvPAmpcnxcPplXy01AVQEBN7GfnFHo1kar+XAwr9ObusoqXWUfzoJ0H5nlsHFgGRwu9MIAqhOzZpIehkUXKW5IevWdhf66YUQPJjcwDht059GvwdhPIevN8z1EH61z2NVv/kl/y7JkxfJun/9R0rJDfdMzXXB9cK7Mz97PQGGzajveiOzPVGkbuKTO3qT5Y1XZG3iGHNYo3NhaIKzEb3j0pGulSCwifcjoQr93ZyGsM3630cpDy++a+Ku6L+FGB+wGRe4uHD/T/R/vrpkX69WOA6Q005Oiud0MrVQwbQFN8IckBXyLNU3moEzXw39zSjGux6sV6+6lRk504001biIuN4D+GALjhhynPDYrLN3P1sD/FmwwHM/uyb+zDqXN7c0Ldc8OtOt9R1a/NlyxhQuayyMS0vvb22DbRSQ30vcu9i8M3/n7iGZ43V41v5aJ3ZXzP4sYWNxITfpPrj7e4EMM52IOqUYvfQ8U+vE7078r1wEVBOMFnZxP8cgKoy0GdFyil472OqkQAgwA6xBK84PtBOdd871WIwdQwW67KmuxjLfd7Yzh0odEz3Fi9IWMSS2kxU88QlpMfnzMVe9ZKNDbFqhuFgysEYSea2q6gilWgfsi1CPXVn6bSs6I+95LwGJCJwNbnusY9uH84bHvqbvgs+OAclKXxIoYzgdDGMSqzmq3OoWaOfWEiqoPiQKg73mgrHLy3/TDOfBU/uzMdTJr9MXQfV4UC8twcuCEqqj7Q0UoZXGdv0CbFebMthctTge1UAArA5rUp+ivGC
  template:
    metadata:
      name: pocket-id-secrets
      namespace: pocket-id
