---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-public-tls
  namespace: jellyseerr
  labels:
    app.kubernetes.io/name: jellyseerr
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: jellyseerr-public-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jellyseerr.mulliken.net
