---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-vpn-secrets
  namespace: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/managed-by: argocd
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBFDJEU732hh0SRKUntYa1fJ30GBVXLuijLRvkP89DoSEaOdUgtP69S+W1iwLlpAGDsvpDTR5LBqvaFJQd1XTa+a70uxElUqhw0vnVpy2RyDWg5j+9qoAxXeLLCc/eLykgcRdOr5PAx6QvY24Uf5xuw8Ncm1NTknKbHoQu9H4MIA4S9TZ20IYlhzqyr+OwFEyytVKG7XG5cjiEySE8ouoIhhkCFYM+XMIPTv8/KiL9UmnuADdjHyBzU7qJld/nfZF0X8S6Ij/8xyHG+bHF55/geGnVp47TZ7JkO3Xb04RQOoeFx5jzPxWe2SXM8LSyQuZ+NSs2Fb5McRNmjiw8LUZu22YUUAEtFMTl948vJ4+gvzMB6tO3Z61X40wvQpHXT2MdLTdiiyBKqtO9ZCJ0REKOdk4RZiwIFYxHReL0FNzNaJ21lq94qj4QzwOy5oiVosQBQitaHDjoYh2gt12FsMiPHTV6CnxjiZX6enWlAGcrk2UhGh29UQ/jpoafTXb3VG1Q7OKZuLj3+15F76VDnMgUxpRNecKTW5EKpK2y//FcXfSmaAIU1fQY+2JE7o/yHaK60UEQvyUMvHwNw7bJh3UI8lL3fzE9bGzMCtG4lV4j4HksyMHxxob2tn/L2p4mQiXOi+ZnDdba3zXj4AOaM/QjWTfLoWzlALYdqQ9OQvYWs/tseOuWueD2G1jqyTGCsA/SBUIdGe14dmVYytmQGdgAe5aoWDrY11ccct/+TC81dtxagk5sVw+xbQGGT6w==
  template:
    metadata:
      name: sabnzbd-vpn-secrets
      namespace: sabnzbd
      labels:
        app.kubernetes.io/name: sabnzbd
        app.kubernetes.io/managed-by: argocd
    type: Opaque
