---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-tls
  namespace: sonarr
  labels:
    app.kubernetes.io/name: media
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: media-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sonarr.corp.mulliken.net
    - radarr.corp.mulliken.net
    - jackett.corp.mulliken.net
    - qbittorrent.corp.mulliken.net
    - sabnzbd.corp.mulliken.net
