---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloads
  namespace: sonarr
  labels:
    app.kubernetes.io/name: downloads
    app.kubernetes.io/instance: downloads
    app.kubernetes.io/part-of: media
    app.kubernetes.io/component: downloads
    app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/description: "Download stack with Mullvad VPN protection"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: downloads
      app.kubernetes.io/instance: downloads
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: downloads
        app.kubernetes.io/instance: downloads
        app.kubernetes.io/part-of: media
        app.kubernetes.io/component: downloads
        app.kubernetes.io/managed-by: argocd
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      initContainers:
        # Create required download directories on NFS share
        - name: create-dirs
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /media/downloads/complete /media/downloads/incomplete
              chown -R 1000:1000 /media/downloads
              chmod -R 775 /media/downloads
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: media
              mountPath: /media
      containers:
        # Gluetun VPN container - all traffic routes through this
        - name: gluetun
          image: qmcgaw/gluetun:latest
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            runAsUser: 0
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: downloads-vpn-secrets
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: downloads-vpn-secrets
                  key: WIREGUARD_ADDRESSES
            - name: SERVER_CITIES
              value: "Atlanta GA"
            - name: SERVER_COUNTRIES
              value: "USA"
            - name: TZ
              value: "America/New_York"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "8080,9117,8191,8085"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            # Use K8s DNS instead of Gluetun's loopback DNS server
            - name: DNS_KEEP_NAMESERVER
              value: "on"
          ports:
            - containerPort: 8000
              name: gluetun-http
              protocol: TCP
            - containerPort: 8080
              name: qbit-http
              protocol: TCP
            - containerPort: 9117
              name: jackett-http
              protocol: TCP
            - containerPort: 8191
              name: flare-http
              protocol: TCP
            - containerPort: 8085
              name: sabnzbd-http
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        # qBittorrent download client container
        - name: qbittorrent
          image: linuxserver/qbittorrent:4.6.7
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: WEBUI_PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: media
              mountPath: /media
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        # Jackett indexer manager container
        - name: jackett
          image: linuxserver/jackett:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: AUTO_UPDATE
              value: "true"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: jackett-config
              mountPath: /config
          readinessProbe:
            tcpSocket:
              port: 9117
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        # FlareSolverr proxy container (handles Cloudflare-protected sites)
        - name: flaresolver
          image: flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: info
            - name: HEADLESS
              value: "true"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        # SABnzbd Usenet download client container
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: media
              mountPath: /media
          readinessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 6
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: jackett-config
          persistentVolumeClaim:
            claimName: jackett-config-pvc
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: sonarr-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: downloads
  namespace: sonarr
  labels:
    app.kubernetes.io/name: downloads
    app.kubernetes.io/instance: downloads
    app.kubernetes.io/part-of: media
    app.kubernetes.io/component: downloads
    app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/description: "Download stack service"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: gluetun
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: qbittorrent
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: jackett
    - port: 8191
      targetPort: 8191
      protocol: TCP
      name: flaresolver
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: sabnzbd
  selector:
    app.kubernetes.io/name: downloads
    app.kubernetes.io/instance: downloads
