---
# =============================================================================
# Ansible Inventory - Kubernetes Cluster and Infrastructure
# =============================================================================
# This inventory organizes hosts by both function and platform for flexibility
# in targeting playbooks and managing configuration.
# =============================================================================

all:
  children:
    # =========================================================================
    # Kubernetes K3s Cluster
    # =========================================================================
    k3s_cluster:
      children:
        # K3s Control Plane (Master Node)
        # Single Raspberry Pi node running the K3s control plane
        k3s_control_plane:
          hosts:
            super6c_node_1:
              ansible_host: 100.116.124.84
              infra_static_ip_address: "172.16.10.10"

        # K3s Worker Nodes (Agents)
        k3s_agents:
          children:
            # Raspberry Pi Worker Nodes
            pi_k3s_agents:
              hosts:
                super6c_node_2:
                  ansible_host: 100.117.19.35
                  infra_static_ip_address: "172.16.10.11"
                super6c_node_3:
                  ansible_host: 100.92.106.48
                  infra_static_ip_address: "172.16.10.12"

            # RHEL Worker Nodes
            rhel_k3s_agents:
              hosts:
                rhel_node_1:
                  ansible_host: 100.94.237.61
                  infra_static_ip_address: "172.16.10.13"
                rhel_node_2:
                  ansible_host: 100.71.45.39
                  infra_static_ip_address: "172.16.10.14"

    # =========================================================================
    # VPS / Cloud Servers
    # =========================================================================
    vps_servers:
      hosts:
        rack_nerd_1:
          ansible_host: 66.63.163.116

    # =========================================================================
    # Standalone Super6C Nodes (not part of k3s cluster)
    # =========================================================================
    super6c_standalone:
      hosts:
        super6c_node_4:
          ansible_host: 172.16.10.51
        super6c_node_5:
          ansible_host: 172.16.10.142
        super6c_node_6:
          ansible_host: 172.16.10.140

    # =========================================================================
    # Platform Groups (for platform-specific playbooks)
    # =========================================================================
    # All Raspberry Pi devices (useful for Raspberry Pi-specific tasks)
    all_raspberry_pi:
      children:
        k3s_control_plane:
        pi_k3s_agents:

    # All RHEL devices (useful for RHEL-specific tasks)
    all_rhel:
      children:
        rhel_k3s_agents:
    
    # Super6C nodes
    super6c_nodes:
      children:
        super6c_node_1:
        super6c_node_2:
        super6c_node_3:
        super6c_node_4:
        super6c_node_5:
        super6c_node_6:
