apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - storage.yaml
  - deployment.yaml
  - rag-api.yaml
  - rag-api-postgres.yaml
  - librechat-config.yaml
  - librechat-postgres.yaml
  - ferretdb.yaml
  - meilisearch.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
