# Minimal LibreChat Helm values

image:
  tag: "v0.8.3"

global:
  librechat:
    existingSecretName: "librechat-credentials-env"

librechat:
  configEnv:
    ALLOW_EMAIL_LOGIN: "true"
    ALLOW_REGISTRATION: "false"
    DOMAIN: "https://chat.corp.mulliken.net"

nodeSelector:
  kubernetes.io/arch: amd64

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dnsimple
  hosts:
    - host: chat.corp.mulliken.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: librechat-tls
      hosts:
        - chat.corp.mulliken.net
