---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: photos
    app.kubernetes.io/managed-by: argocd
spec:
  encryptedData:
    postgres-password: AgA31Eb9KAWAZExMdUQ+qcZH9TMvzkp3E6EnTLR3vWRNg56v24umXVpb42KY5wF2UiruGgsCXq2uBN4dT0txgApLoGiv1ItHjhAw4khPB/SJlPsAk5YEyuhaM+/qrJ5W1YBHVbYxQ0DNYfC/Bu4y0SdMX39GLxlpX3LI7xjZdMyTot0nfm+5Rwc5mbHC1+Cm0k1V/w+VLKW0XlgRvHtTDsrR7djk67VqIwSf/d5zRu67d2FxGBoMtVXZZbRKvJjFyOysXu12JRZCLROTlCr3LcsblZoej+Niep3RE+GC4MPwXjiRh9lAP6RGiu93+bTmrI/RaeQ8xjezpuroGqtimqqk2YGmV5uC+q0Rf/AeO+88+rSBOxSeQbQFSDa4RilEhJULKL3+FId1+YQ4+sAUQxqcp2lLLKSW9JLPl+0jFMvNcejvIp2qemDj0VZIEm+4I8KVT1mBXrDMCK5mEQCSn3YQTHXp0mNTJ17zOtgVTJT1yeKAuAxM/xwvSXm4E0vVe5WKRqRFuTImHWVrCNOo4UHJYN/Eugx3Z3VwqycHpUHRKLn2criHVM9ZAd7jNhv/G1K4mOHyr85VHrx01DLACwzVKghweZaWgtnCMuBZimpQHnStI1DjNLfCjEFlE2CxbA7DcexxImfhpasKKCXpnLyeNLu28bzMnfmF6wsFR6E8l3w4Tg5vq+OMxQ82uKvaahOmS1/BsWT1loX6N7nz1sn4Zd0HfbLps1nlo+5pXgcoDDy0yzY7Ng96oJk1
    postgres-user: AgC1yIM4Fje55je2awNmiUcwvhLD+TM95ZBIHvnDqKa7iUmo/aPo/en/ueNautXWc6FdxcJyqx/O1uV0VBeSpfWs5Mq2g7bL3sX9DRN17Sfba3IOKEV4nRDKv3x/FUspPlFTjckHoZK/bnQa9pg5UxoiFwApE/iTl5lSRnsUDoOSCVa3/hji1BQsx4D6tpnwMHFis3VraBbFvAEqCphA2Cvs/nBoXA6Ju38nNl4IYgW0oTB4c4/NDR/ZmimoFJerlNFUskdWt5Z6n8sKFHSMf5oChsEFJayu8v3Y+T3PPrm9SIHkXK0X0wR4AeUycm72/Ro3Tla8cTFy7BVHcN86vNAdVZUVRwywXLT8BhuV5x6byuoNPWN6+d6TcTrbAjrmk4NuiyjvEIOxbD+FmArn6q6ZH79M0ZCQYJxfCJO/AWZYTjC0YCtTV5PzC/sCz+qp5Shk6APqgmnKDPM9se8sjOYUTs0ZqrtQrPWLM/KXJQmLm3kBWI6qFevnvsp2toEEJHADXZcHP89S7zO2FUXgB46On1OeogRQdVmRFbsbPLJd2xQHfgLdXuJKFIYZS+udZ3Fb1kQ/Mamen698tN0oaqh29MyWwEu5bkd/JaxT5A0HU7zYjmGb2OzvGf8YHzT+RmAXtiGXwps1jqGmHqM6mCKVZyhMXu0583nJftuNK2T6PXDsRVzntI78c0WVTm9NgpjdnwBVugY=
  template:
    metadata:
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: immich
        app.kubernetes.io/part-of: photos
      name: immich-secrets
      namespace: immich
    type: Opaque
