---
# NFS Persistent Volume for photos/videos
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: photos
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-immich
  nfs:
    server: 172.16.10.248
    path: /volume2/immich
---
# PVC for NFS library storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: photos
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-immich
  resources:
    requests:
      storage: 500Gi
---
# PVC for PostgreSQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-postgres
    app.kubernetes.io/part-of: photos
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
# PVC for Machine Learning cache
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-ml
    app.kubernetes.io/part-of: photos
    app.kubernetes.io/component: machine-learning
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
