apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Required for Kustomize `helmCharts:` / HelmChartInflationGenerator support
  kustomize.buildOptions: "--enable-helm"


