---
# NFS PersistentVolumeClaim for Paperless
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-paperless
  resources:
    requests:
      storage: 500Gi


