---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless-public-tls
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: paperless-public-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - paperless.mulliken.net
