---
# NFS PersistentVolume for Paperless documents and data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-pv
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-paperless
  nfs:
    server: 172.16.10.248
    path: /volume2/paperless
---
# NFS PersistentVolumeClaim for Paperless
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-paperless
  resources:
    requests:
      storage: 500Gi
---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-postgres
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
# Redis PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-redis-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-redis
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
# Proton Bridge PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proton-bridge-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: proton-bridge
    app.kubernetes.io/part-of: documents
    app.kubernetes.io/component: email
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
