apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-tls
  namespace: litellm
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: litellm-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - litellm.corp.mulliken.net
