---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secrets
  namespace: litellm
spec:
  encryptedData:
    litellm-master-key: AgAmwvAbwDhcd/TeK+aT569c6f9C4KVjH/fleAyeG4KXvhtrvRObwbXXjcDB3dRMEK2+G/znDP9NUp9YvVZiVt8VLvQyORmmltVgp48hL/PJbeQQRMQ2nPU/g58Rh0OUnvMijyCzQG6HAIh9z2ul/FSfd4QWQDLLbMdkq5tHSEYJ1+ktgxs6iDgbWw9qf1SemiUhnQllBKYNAU2wThIFYeesFQygL0ZN5TA6fbNKREw3tvjo6nn6WX7K+9i/zkL3FAZKjktNS2Il9BV3beJhj2X32JaOTlb/dxfU7U4Ubu1IoCdHA2otv/mFYkeP2xysX+HYPNKkU8cpCZi8QNPz5wNzRR2f7lPG5AXJ4Cl15Iu4ZDCUNf/e/U9sjn4Xyktp7Ze6wJIV+CbujIK3Fu6aEyTvrG3M8Kevp3fGfcWG9QsiplxiqNjpuKs7fy168fNiFaIvUp8aq0XMfMUJh5gwUpWPKa8Z5EdJpfxK6woQVychn6JNO3jtSHDlrNNPEYYKsQqF/HIRKobVyftoHWdISNkAL5bHD7O4v5GMWUFsCXVr2n9wNUPI1FGwvD22ADObzhMZ4ZkEqYpXoDeGj3rG1jQ0WEe7iiaPA0qA+sEBFOqf36REvjPnElKgKG6tu8LEhpsyvtsDep89/DLTj5K9erZqvW0vrnyn5O66wo02Pgb27ckBvasS9r6fsg0kkH73ZEM=
    postgres-password: AgA7rLaECvzIfir22utEPxyS1uw/WHhsSMC8UFNGVJh4GSAZtotahvWkNvVrQB9p+IOw6YrE+16cyoNX/7gKZyrUc0x/UKUR8s/JcpBMOHvZ3uZuLKVqpi3cRd56EpOtKCjBJvHV5xPEO9WZEPB0DawcUC4hJfiLZ4c5lGAVjw4zgrbVt6Lpt0Nw2ZZDFq1RifWSXV+5hMat0TQgkK6ioeSuAOW/2XNFp9YuPEfN/uHbV4CcHV018SUgCY+ziyT1jS+aj50ySIUmM9ames9ZLPSBn5v2w6ZmsEYsr4iMsKbi6yklhzMsKwoEXuGU/FDxxVpDpO5MpzZkEiFsD1bS5h6QDaAI+0eNOrKewT9GJ1Yri2TJk3BbHE/t+1bv1Q5XLDToXY0uX39KNcuUOQkEGNtmYxXWUnp7mL1H6RQ+tKQHcpXMPccpoDca+GmFOxJGXScYYG69aWts3W2Qd+Q3fEcgVhzsDyo7vfvco1CtPCRV6nNiZwQCqsoAjOGBp/koPFNQx9vWG/wylM27ytFVjZspFG5u+VUtgiBtBML4V6MHteclBRI4EQV3ej2dLxrMeXPdi1TeLytHYoCTT8Eif4A9orEHwK3oQqL896/qCG2ND3U4C/AycFgXGkCn3ffgBsTZhuFNFBoAuqSBpBiuodxOuhcfoYNB7yo35Cp+xRoMPETa7K75yu9YoIQCjmQO/qs=
  template:
    metadata:
      name: litellm-secrets
      namespace: litellm
