---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secrets
  namespace: default
spec:
  encryptedData:
    litellm-master-key: AgAw6XpbKMbJlU/yKBeNGHFKH99OqXubm96DDdTpCRwzoteWbuOCdwtusq1hzex2FOwj2dYNl+gPp2Z1i8+oWcDLY5RJgWabYrUu263rdeXYiJzdgYATAxuA4YQSTAsH6vTq7wIyYpoAsW7QM9LC2FwxghzIpCm+Y75+9ZcPyyknomjYAUYb9lxpvZUhdedpaTDW/QuAJGfX3DL8M4jeBavdfEV46mZZ+86kDrIGk9Mcn/KfKPF8ZvZmk0UdHqNAl3KWp9TKa5Ifx+Ngv/njiZZGOVPeJkilzX33dDKMeJ2qONag/9E0+8KgDZZEBnxrdaIPBRifkR7g1hGknq12IHcqx84JG7GEfjjtj+H2O8z8lkCn2kLpxh73XM6jtf7Hz83auWe2c/AvEUnotnD1J9AjoZJYyPn0aFY8wtRV8Z5YavyjKJe2twt79GBCZ8b1C4QRCHhwt2S7uX5/lgV2mE4jRr8SrEMghK8Kcsmj4RKFWEh0YLdbIqV4hHF2AHKlrwEkj23VREYYzMDAJYTXZ32FaXHTgmW4dCGKJPD2HJkQ1LwWbkOCL8IXvTi1KebvNZ7OX5RnA1LZHv7fvNGyH6PSkqysU75buDdugX78awFGVVi0bIeNDHZFbfRH6bi90hF6Ue94qZ8rb7HIu/zbVxo5hqGVWhfuxqPhkxKi4gywHj/aMswKaHedLfDW8upxQMg=
    postgres-password: AgCZ7ApbGPB/ZIIpDMvzJ/FHrN5yX1hG1+97FpJROfcUoqF0PS/0DHGO9NNdEKDNwV0kkWdiomXEvHGRh5p69j3FVbUvlj1RPbJwuSQfo3whxH3Y6fTO20q9rYKuIPnfxOZwg9KMxrXaFWpYteCO7nxiDFH5XG2jEGqlmupWlYDP6yHq+QsdIwgbyrKkESDJ5+m5Uyp3hG1ztAjjdU94295wBY0iC8c+HOZf11UW7B7qORqVWkf1yTmJSJXIk9NhBI4veMpC9DqUsCeiwMkwGoQXmPuDSV+u6a0GPV2eV/f/z2UaeOvPFWAHhuFZfPqtZtMqqbyhP54tMkataeMIWTDyMv6FzBNhWdfyYoa4ta6wZTaiziDYyBKCNIdRFxOMc0YySos1jXd6mYWXlCFtPCmis0N56jaDfSBwjmV300/2J6jNFStQx9xtipDB0i8Tm5beFhTaqvJomLbuOZTNI88jc1OnZPnwYGAl/yB3+patNst63/8NhstEtHl0rQDlYjWCTaPkDBuwrX0/1LxUd2Geqsxkk0A9QvKGAWJ1T/gGJLq4/NqTHYCnck97XU4Gt27E/Bl4G47hhNo4DQ5UkwhWQnK4cfASfTn90YACiY/Rfpd0yVFj2bQs+pnzD5rXJa30bdyrBYEWWOy3TFN7JjoqhoAOLRG/I6u14CN+4ClmKoJlWyldkwaqrzYHMejuqPE=
  template:
    metadata:
      name: litellm-secrets
      namespace: default
