---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns-updater
  namespace: dyndns-updater
  labels:
    app.kubernetes.io/name: dyndns-updater
    app.kubernetes.io/managed-by: argocd
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: dyndns-updater
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
          containers:
            - name: dyndns-updater
              image: alpine/curl:8.11.1
              command: ["/bin/sh", "/scripts/update.sh"]
              envFrom:
                - secretRef:
                    name: dnsimple-credentials
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 50m
                  memory: 64Mi
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: script
              configMap:
                name: dyndns-updater-script
                defaultMode: 0555
