---
# Local snapshots - 1:00 AM daily, retain 3
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 1 * * *"
  task: snapshot
  groups:
    - default
  retain: 3
  concurrency: 2
---
# Backup to NFS - 2:00 AM daily, retain 7
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: backup
  groups:
    - default
  retain: 7
  concurrency: 2
---
# Weekly backup to NFS - 3:00 AM Sunday, retain 4
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 3 * * 0"
  task: backup
  groups:
    - default
  retain: 4
  concurrency: 2
