---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: posthog-tls
  namespace: posthog
  labels:
    app.kubernetes.io/name: posthog
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: posthog-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - posthog.corp.mulliken.net
