---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls
  namespace: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: qbittorrent-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.corp.mulliken.net
