apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-site
  namespace: argocd
  labels:
    app.kubernetes.io/name: personal-site
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utilities
  source:
    repoURL: https://github.com/SecKatie/infrastructure.git
    path: k8s-apps/utilities/personal-site
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m


