---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    ntfy-token: AgBhzVCQOL6D5dB9iR2Fg4B5vp9PKelOd7tz+PN0KEGLevqmSNEg5JWQSjBUK0rIJNqEA+89kL6BVQWlw+gn9NeXgDepgbD/hPg9SJZtuVcADNpkYcK7Og/29NGcJIGsdwDuH3HNa/IzJWAf6hmwr1JgPqNcLbZIQ0FeMZ5fdwnkciKrvfY9vj60zIKe9uGLjaCMhDmW1L1uBqwOgVHkQBTvdeGaP6yK6/Q0D2TNYBkOZaoc8u5hW5isZrX+AZ6jwsv4RXg23m4+K7LNkAjppEtWMFZzOSNHqNkmVl415BWSYwZpF+qdhBnfgODrp1GASSta1ThIL1K0an8+8lTMfmlLr59RnJaknFcJ5mrRn+Qu45mpKhnjdfJf3BcTxGpuPSvRcsIkJqxRUhQJxDwWB6j76nAkn65OCSmJgyBMle/iXd0vRqiKfGJdmTDeHcrLz8av52c9OE08FBDa57JXNuQd53s2+5lRXgvey+IzpnMSciM6AIZUy7VoSpqDaTMQ+myLm967CIaftx9FenFXEo1AKnFf7w/36+mHsmMKbqfhkMa9/ZzG7XWtLOLavLd3qsA+WZWbD7mEc0fIbTTufiEGn1UkFZ9xxFatl4UQB2b4q59Zj1KvO//3LF8aFy5eCwyAuqmHQexPuiHPf15/30yp0cgWNjxkEQnimkwUBWXPcdJEmABdnYo2jYL7w3oNem0wDBwnNjUr091fYE9YLPC8aUwkWI15o6O0kJf5Rkmyaw==
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
