---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgBrtI2oN8nwnds2oGFNAXAF2KQ05DxjJmgxhz2AsCA32rf5iQni30jJC6QWDjdsw9A9LThad9Tc26GtK16GRL+QZ7rP0nZg4n8Mis1Dn4cEyTwUIq8MV+UH3V0Xc5UjnV680iBqYrxmhsRB+VauaTcP8Qv0mLGxAzr22hKTtGX/CQCNm0RQaNHVwUFH6FxNkmXtfDi9zPRAEJQ5ohW2nU+OS13TMPVUHReES0ihcg7eCNcDKcL5hy9D5tKxQJp3INNZvS4M+5rswZSmJPsy4o0Mz+8CCpLtoJ7NKInBZX5IxkTTkzjiBGULkw2Z6GVkU3MzjeFotAHBWx5kT6LYUhit288lZyp34h1I1urBvdjqFkUgdjoyJbGzMvuox1H4d72rJuge7t8h4DsDHkygTZcTQa0omzsS3HR/ztZcQNoaBg9yp9IrrAENfGeEbS1GoqsKrGIJU4kdNqtVpToEjc023WVyN/Ks5LIaqxuLiFy09DNo8ijAkkpp093SPM403lyMfVhNN0Uuh32iGVZ6oxB6i4d9Skdzh0qgwqqlojG7WVIcKcJQ5RAp4bqfj1JZuI4Rp1uf4jphbW3a6fVHxOXdp58kAGXCUCIznq3wfNtTJy4f92SdzB5tgwkA7OIJFkLNzsUMyEzyEGXh7qmwp9Dgaw9xQsecNrVpKWFMFB/h7db6hy8quBBxD3yFMYhkeNZYQgX9O4uV1mkBdqp0gWVKVOeT1tyIdHKhmPnd15YBS8gsLEyRQikchkOPzBDqKoyDxnQNqu352gHHeIgTcFz0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
