---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
    app.kubernetes.io/component: indexer
    app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/description: "Jackett indexer manager with FlareSolverr"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
      app.kubernetes.io/instance: jackett
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
        app.kubernetes.io/instance: jackett
        app.kubernetes.io/component: indexer
        app.kubernetes.io/managed-by: argocd
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      containers:
        # Jackett indexer manager container
        - name: jackett
          image: linuxserver/jackett:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: AUTO_UPDATE
              value: "true"
          ports:
            - containerPort: 9117
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
          readinessProbe:
            tcpSocket:
              port: 9117
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        # FlareSolverr proxy container (handles Cloudflare-protected sites)
        - name: flaresolverr
          image: flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: info
            - name: HEADLESS
              value: "true"
          ports:
            - containerPort: 8191
              name: flare-http
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
    app.kubernetes.io/component: indexer
    app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/description: "Jackett indexer service"
spec:
  type: ClusterIP
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
    app.kubernetes.io/component: flaresolverr
    app.kubernetes.io/managed-by: argocd
  annotations:
    app.kubernetes.io/description: "FlareSolverr proxy service"
spec:
  type: ClusterIP
  ports:
    - port: 8191
      targetPort: 8191
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
