---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: radarr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - radarr.corp.mulliken.net
