---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: perses-config-secret
  namespace: monitoring
spec:
  encryptedData:
    PERSES_SECURITY_ENCRYPTION_KEY: AgAUFkq50GbJgglRsrq8H/OKWIu+wO+ZkGqneFPGnokYO2+iIl72LglwaSx9951JHvmX5dDm6kdlFq5vRguBUAOGm8uAsxNEiSWJonRZsXJIK30BWCU/UQWh9jUYPP4UN/rOfH9bzonezYaqODb5bQekUFFY5CLvoGKNX/WAZySEjN1b+hBP0lT3hZBbDaUqPJy1gM0Zx8QxnTFyH5T8qSxtjB4URSeDD1+N0zzwsTejSF/tfjy7OsNZyZ23V/VfOZGJOwTDPRD848B6Bc9siotlTuCzb+ZKapLTEKJpVEZA660Zqj3YB5hZrtQpueqSVfwmtyCzzDzArY0VpIJHXiWa42cJtcT5yqcp9zaPfUz8I2AdsgeKO/pSYSiWrKOILcgEYI0DH0PkDt8cODKzw4X/mVkAxjuno4+81d17+R+iPvWBMa4cDg1aFV2jllbZl8T2immrY6qhukXEx6eT/SzJZH88vK3lgszQ/4yFx4l0BRMR8rCzPrNB9GPo5dXPHnR6PiEyVoBTVhlZy7VWSSsojfO5sEFYIA/U436dTv4VY6Dr4WNSWXrL6qdggWYmAZ/ndNZweJOqFaSTdd+2oJsqHMur/H6uxhqaDnGPKEWxzqt0qdIzrGBByQmyB0xshzyjzQJJiVWKQCdR54ISG9cWZ7B1zGOo+QtIgqhZaH/mWws0E4zjSfbc/07MZMlBzIc7U5llvjV9TCffSSCUDvUW4qhVcPbHNCanykZBo9YZI/zhnfsLVSBpsBnxDw==
  template:
    metadata:
      name: perses-config-secret
      namespace: monitoring
