apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-postgres-data
  namespace: litellm
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
