---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami-public
  namespace: umami
  labels:
    app.kubernetes.io/name: umami
    app.kubernetes.io/managed-by: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kgli.tc
      secretName: umami-public-tls
  rules:
    - host: kgli.tc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: umami
                port:
                  number: 3000
