---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jackett-tls
  namespace: jackett
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: jackett-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jackett.corp.mulliken.net
