---
# ArgoCD Projects and External Apps
# Apply manually with: kubectl apply -f k8s-manifests/argocd-projects.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media
  namespace: argocd
spec:
  description: Media applications (streaming, downloads, management)
  sourceRepos:
    - https://github.com/SecKatie/infrastructure.git
  destinations:
    - namespace: jellyfin
      server: https://kubernetes.default.svc
    - namespace: sonarr
      server: https://kubernetes.default.svc
    - namespace: radarr
      server: https://kubernetes.default.svc
    - namespace: sabnzbd
      server: https://kubernetes.default.svc
    - namespace: qbittorrent
      server: https://kubernetes.default.svc
    - namespace: jackett
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Monitoring and observability stack
  sourceRepos:
    - https://github.com/SecKatie/infrastructure.git
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: utilities
  namespace: argocd
spec:
  description: Utility applications (dashboards, tools, infrastructure)
  sourceRepos:
    - https://github.com/SecKatie/infrastructure.git
    - https://github.com/SecKatie/personal-site.git
    - https://kubernetes-sigs.github.io/headlamp/
    - https://bitnami-labs.github.io/sealed-secrets
    - https://charts.perses.dev
    - https://kubernetes.github.io/dashboard/
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
# External Application: personal-site (from separate repo)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-site
  namespace: argocd
  labels:
    app.kubernetes.io/name: personal-site
    app.kubernetes.io/part-of: utilities
    app.kubernetes.io/managed-by: manual
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utilities
  source:
    repoURL: https://github.com/SecKatie/personal-site.git
    path: k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
