---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victoria-metrics-tls
  namespace: monitoring
  labels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: victoria-metrics-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prometheus.corp.mulliken.net
