---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: umami-tls
  namespace: umami
  labels:
    app.kubernetes.io/name: umami
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: umami-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - umami.corp.mulliken.net
