---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-vpn-secrets
  namespace: sabnzbd
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgBkUr7MhQ+0tKVHCWGytTuwohZz2s+IgYHTJehra34KdqwKM8sRxvNN4BOqY611tLFd1P4ZOee0WH0xtR1PNNX/L4Io1JpV2ba620bJjeAmm1gmoYSICUQpNIRyXy+QEa6BugYdmEprGcSygpTsBSrkBIsBY5Zi1j1x2UF0ByW9tNcyJdMAKFMEpZjXctnnmPKmGGKXu2dP+rmW5rRfmUtruI6dONm0A7PIP12PmYvVetYbF0xMM3T0kREzhh71C0YcsqrhiZ3UC62LcSOTktjGC53f6ZU23ROocqZvlu+h547G95KmcACCxXNataTZdBFPfcpH+AFZ/0+aUqAOwnVlt0RWFXMvVGaTozhEvZzzE5XwWwjki0fB0KvX6fyAHNcgcsXxL6+y8x0I/Jxsi3u2DQe7pnsArqZNnX7mMJNHnDsscsi6pxtNTSNCfMUdlJzIYWwXAggJPkoCbnwV6vzyfb5yxUdWYP1UFXE19XfxYyrCyjcg8/ULFHWvBDmiABn5S6c2OXvXp0D4bOXMF3ZITEIunO8xXZftKgpL2A7YHzhQ83jaKn+WlwwPa6lSTzKlUzeFzDKZg5v0vyciREJZGlRiaO5UO9I1H1CZzCR/R1mej+QlZcGhHhjkKBgGomUECXDwAwca1TKUP121jONUUUffLx/GFvDF4X3INZ4qvqFkvJTTVjX/ti1i2gUbx+VcvAEd1WlGu38Ls41bcfk9nesIDp5Bjxf8qlqH/v44CKxR8uYxt6RXCRN3mA0RwA==
    WIREGUARD_PRIVATE_KEY: AgB74JPMLxBWPqL9qx3/4pS0V8rfn4lzVH94vNU+k/gCc6REAnwW3DIMOVZJDgE+Xdrw+TS2bwA3adFyW0tuzgqGTSfS9GL5qFcgBSzjyv2b9ncXvTu6IM3Wqm6uNYSzCI8N8RzCu+RhOKnWL06ykde1eWcJUpbQUzrKpbdEEmcM5IFte6DmowWvUNZhvyLkPlV3a5YzkkL1fTsLHRlwenJl3Uyn6HsldISSbgNeLMEKyu2YIprbBrDAnQQ+MXOkWwPYO8lp9Bxfn9jlATfTutOftQdec+Sk6vW7pG15ZbV7Hn3oUYE+I5QTdLn/oh53e79wEkNfpksA3QiBo+zVu/nesKthBG0nq928kvwcVKtKcUip0ez3l4tOhG1OFaiLxLeGRSiPWOiP8svVX3u5sGRzkhNHFnfveP7QVvnJu04QK2eEk1bpCIIg3OPALw/6p4ONU5af+2l4dG4ECCjA0xnHZBd+uUmO4J684krrD8WRLpTdrs61/nh78+mQ7G1kSAlrOHsNbvjydKq8ERrU4taWgg0/AYU3VcY0nRRFzY5FCMtjvMioFL2VDpw2rpAG2Cg8eqG71FoCeNetG1xMnzCWpikZe+dn5IijOYbPUgeVSQyQpkWLzCDo0YeC0czpxc+dArdlHmy8wpv0NHwbNNE5sRk8KznZ5kUWWHcuwXBuVlMnbG7GU3UY3MwfLSsy5S38oFH+R0oSUOCyvQ35Jk/1jIDL9XTgRr6KOe+xFNJaiivUT4luySrZN3KWsg==
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: sabnzbd
      name: sabnzbd-vpn-secrets
      namespace: sabnzbd
    type: Opaque
