---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - namespace.yaml
  - storage.yaml
  - jellyfin.yaml
  - public-certificate.yaml
  - public-ingress-route.yaml
