apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tools
  namespace: argocd
spec:
  description: Tools like ArchiveBox.
  sourceRepos:
    - https://github.com/SecKatie/infrastructure.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
