---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn-secrets
  namespace: qbittorrent
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgAhF+vr5yCtT7rqpgMqi1NMHHA12y/qCzNJm1yIDRPaai+noGtHz3tcMnh3LNqoSaFtvbul4e9fXHIV7YUTe8QJFnwKLZUccYY08YiyHUu3YDIpK9CdsCHOtcUcaY9bFjGIaKd/T9sdh3dx0Lc3yeeYVcZ8a0XKFaf3i91Ru4kZqmc4nxAYvdttpol0vPprUoBjlFl2wX0cXYwVZ1z9v2lECU7rmqQucSd+0uRmfXDPeuCXCdmwD9W+aYXhl3VE8hKuYA7cP1wdvFGxAvdWlBQ4tPoAh8AlyCljYDl4LMxC3WOy7mBpRJV3Y4fF+8YlHFuVBYrY8psZ5oo4RC4VVjjYoeZhffP0F7fgbsuFnFzN/eR+AmaN11malT9JyDHhM23GjTFNJWlD0d6Mh/hRNgOMp9aGth+02Jwh+uF3MJmxoiJf73NyF1Iq+3ZeZoYhYnv8wdoHlpDffNc3E9HJ5bOP9uO+mbnQLKSGY0bw6scAn+UTUW0oKo48NF6VGxGqLESWFZU0mV99FTEe1G8p/9rBxuO6IaI24nleWUXcRDZmAt4plR0Ta1J1uVqR2QYhoSq4jxIxSY1uQgK2KhamW2wTc+NyRHJIULvDofi2igZG68TtyNPOoh7BnCbRuCHCsKU28QRVnLSfFBeF1196A5+7ZJb29Wbei6gOmQYrdmeXJR4oVf7a/gfopnv8aOoQMG4Dw8H36Uo2h+woAQ221WO/oO9bgWuytbBr0I0puUr2HxX+IB0YtQoqKuEp64+RP40=
    WIREGUARD_PRIVATE_KEY: AgAz2SSNw3e9Xo/BAaZJKQ9HGhCrqHeaSLARDzgA1ZoMKBlqGfiHyT8ldRQ/iaY95XOm1DScBh1LT/feQmgV01shyR2bFt6VaeOFH6ME0FxkMMvRBQqGfLvK7DvwhIt8RzXuITgGAvdXweqNIoa32d3szGLfTve96D4csD6WmdKJnrMlMJouTvgRIFydz3sUDnxwxChPSxKmN2Q7qIH+QOyObpqG8kcrUihre93uAk6CsaibEMpz8JrleT1obXP9gwJVf2NS+bq29ojgh0m6q5adynMyr3P5M3q5iWT21JQflAQv/I4U5veugU8Hwm305IH750jn06MqmFFbMnMdH4rbyRvZJduk9WLXJTQJW8a1/mKGVHw4Sarvww6AdFsF2y8tgzJAuknnwXi+I97L7rHlln4VHZH7ZUcwxphcVCAMZuOaqVJfWw7XbFoXPFsBHSOAex6ecae9+nDukvJnLpshm7IR15Wbdwr8lXeoRv/ttOt4g9qR0LaaHEYFKs6wFU0iaWzNng9hVPV0SbIBooaCGtEtBhGjF2tu4g5DVslXgjknSMYjPfVRCjzgZXVasICLn+sZrOCMPoJRSJYQXwEo5qrOa6yiU1QKNG/3TXHr9VLUmHfjfVLnq4hPl4bkSmDQxDf+bGmu9/Go3S1eC/e4jKI22W4S4g/L6VWs7j/Hja6x6UsxLjSQIiH35BSLeZP3YC1qfaBEJoGM83IxoFc1Dd28XubvkXajke5dZMS9w1n6V1TloXz0RZOdRQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: qbittorrent
      name: qbittorrent-vpn-secrets
      namespace: qbittorrent
    type: Opaque
